---
- hosts: pythonanywhere

  # For {{ vars }}: see docs/anisble.md

  gather_facts: false

  tasks:
    - name: Synchronise media files to app media folder (original and images)
      synchronize:
        src: "{{ app_path }}/media/"
        dest: "./media"
        delete: true
        recursive: true
        mode: pull
