services:

  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: tail -f /dev/null
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7.34
    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 20s
      retries: 5
    volumes:
      - ./database_dumps:/database_dumps

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped
