FROM python:3.10-buster

EXPOSE 8000

ARG VENV=/venv
ARG CODE=/code
ARG USER=wagtailcms

RUN useradd ${USER} --create-home && mkdir ${CODE} ${VENV} && chown -R ${USER} ${CODE} ${VENV}
WORKDIR ${CODE}

ENV PATH=${VENV}/bin:$PATH \
    PYTHONUNBUFFERED=1

USER ${USER}

RUN python -m venv ${VENV}
COPY --chown=${USER} requirements-dev.txt requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements-dev.txt
COPY --chown=${USER} . .

COPY --chown=${USER} bash/superuser.sh /home/${USER}/superuser.sh
RUN chmod +x /home/${USER}/superuser.sh
